### ISSUE TITLE
running issue

### ISSUE THREAD

**Issue by vijaya1109** [illright/flask-pywebpush#1]
How to run this program

**Comment by illright** [comment]
This is a Flask extension. If you could please show the code you're using, I will be able to provide further guidance.

**Comment by vijaya1109** [comment]
i didnot understand give me brief explanation please

**Comment by illright** [comment]
Read [this link](https://flask.palletsprojects.com/en/1.1.x/extensions/). If you have any further queries, please, provide some code.

**Comment by vijaya1109** [comment]
`app = Flask(__name__)
private_key = open("/home/private_key.pem", "r+").readline().strip("\n")
with app.app_context():
    # within this block, current_app points to app.
    print(current_app.name)
    push = WebPush()
    push.init_app(app),

    push = WebPush(private_key=private_key,
                   sender_info='mailto:xxxxxxxxxxxx@gmail.com')
    subscription = {
        'endpoint': 'http://localhost:5004/entity',
        'keys': {"private_key": private_key}
    }
    notification = {
        'title': 'Test',
        'body': 'notification body',
    }

    try:
        push.send(subscription, notification)
    except WebPushException as exc:
        print("::::::::::::::::", exc)`


output ------
:::::::::::::::
:::::::::::::::: WebPushException: VAPID dict missing 'private_key'

**Comment by illright** [comment]
Make sure you also read [this guide](https://developers.google.com/web/fundamentals/push-notifications/subscribing-a-user#how_to_create_application_server_keys). And please, format the code properly or send a Pastebin link if you want to share code, otherwise it's impossible to debug.
